### ISSUE TITLE
MathOps operations do not cast correctly.

### ISSUE THREAD

**Issue by SingleAccretion** [giladfrid009/SimpleSIMD#1]
This results in an `InvalidCastException`:
````C#
Console.WriteLine(MathOps<byte>.Add(1, 1));
````
The reason is that C# does not define operators for smaller types. So code like this is wrong as it attempts to unbox an `Int32` to `Byte`:
````C#
return (T)(object)((byte)(object)left / (byte)(object)right);
````
The correct version would be the following:
````C#
return (T)(object)(byte)((byte)(object)left / (byte)(object)right);
````
This needs to be fixed for `byte`, `sbyte`, `short` and `ushort`.

**Comment by giladfrid009** [comment]
Great catch! thanks for that.

Closing with commit https://github.com/giladfrid009/SimpleSIMD/commit/01788e659b9bc321c77e1dd8a786b14d5aab4f54
